### ISSUE TITLE
The "xnos" filters cannot be removed

### ISSUE THREAD

**Issue by will-hart** [lionel-rigoux/pandemic#12]
When talking about the recipe `filters` option, the [README states](https://github.com/lionel-rigoux/pandemic#recipe-instruction):

> Array of filter names to pass to Pandoc (see pandoc --filter=<filterName>). Note that this entry will override the defaults and **you will have to explicitly list pandoc-xnos filters if you need them**.

In my current approach I would prefer to replace `pandoc-tablenos` etc with [`pandoc-crossref`](https://lierdakil.github.io/pandoc-crossref) which seems to have less issues with my setup and is still maintained.

However [this line](https://github.com/lionel-rigoux/pandemic/blob/master/lib/publish.js#L104) ensures that the default filters are always included, even if the recipe overrides filters.

For instance a recipe with 

```json
{
    "filters": [ "pantable" ]
}
```

results in a `pandoc` command with

```shell
--filter=pandoc-fignos --filter=pandoc-eqnos --filter=pandoc-tablenos --filter=pantable
```

Could it be replaced with something like:

```javascript
const default_filters = [
      'pandoc-fignos',
      'pandoc-eqnos',
      'pandoc-tablenos'
    ];
const filters = instructions.filters
    ? instructions.filters
    : default_filters;
```

**Comment by lionel-rigoux** [comment]
I get your point. Still I am not certain about the best way to proceed. I would like to stick to the convention over configuration approach. 
One other solution would be to have a "no-filter" option to deactivate the default.
Also, would reversing the calling order work? Something like this:

```javascript
(instructions.filters || []).concat([
      'pandoc-fignos',
      'pandoc-eqnos',
      'pandoc-tablenos'
]) 
```
This way the default is still called (no need to specify them in the recipe) but it should not interfere with your filters as no marking should be left after your instruction filters are applied. 
This might still be too confusing, and something in line with your suggestion might be better in the long term... In which case I would go for the following:

```javascript
const filter = instructions.filters || [ 'pandoc-fignos', 'pandoc-eqnos',  'pandoc-tablenos' ];
```

Last time I tried crossref I had a lot of issues. Maybe I should try again and rethink the default alltogether!

**Comment by will-hart** [comment]
I don't mind the "no-filter" option, however isn't that still a configuration-based approach? I suppose you could also go the other way and have a "defaults" magic filter which adds the xnos ones in i.e.:

```json
"filters": [ "defaults", "pantable" ]
```

Reversing the call order would probably work in this particular instance, but the filters are still run, contrary to what the README says. Also it would mean that if for some reason you don't want to run the filters* then there is currently no way to do this. 

---

This is a particular issue for figure captions, i.e. with pandoc-tablenos I get captions like this:

![table](https://user-images.githubusercontent.com/391950/50568582-0ae5a600-0da8-11e9-97f9-bd53f454cd5e.png)

The red "Table 2.2" is added by the LaTeX template I'm using and is the correct reference. The black "Table 2" is automatically inserted for figures / tables by the xnos filters. There is no way to stop these filters from modifying the captions in this way. The number is incorrect as pandemic is only processing one chapter at a time at this point and doesn't know this is chapter 2. 

Actually, thinking about it, its not clear that pandoc-crossref is being used at all in my build, as I guess the xnos packages are being run first. 

---

`*` I'm definitely using pandemic in a bit of a non-standard way for the thesis which is where a lot of these issues are cropping up :)

**Comment by lionel-rigoux** [comment]
After giving a second though, I realise that of course you are right.
I do not foresee a case in which someone would specify filters in a recipe while keeping the default, and my suggestion does not make a lot of sense in the end.
Following your recommendation, filters given in the instruction should completely override the default. Specifying an empty list in the instructions will therefore disable all filters.
